openapi: "3.0.2"

info:
  title: "Cities API"
  description: "An API to query States & Cities"
  version: "v1.0"

servers:
- url: http://localhost:3000
  description: "Development Server"
- url: http://localhost:4000
  description: "UAT Server"

components:
  schemas:
    states:
      description: "States"
      type: string
      enum: [
        "MA", "RI", "NH", "ME", "VT", "CT", "NY", "NJ",
        "PA", "DE", "DC", "MD", "VA", "WV", "NC", "SC",
        "GA", "FL", "AL", "TN", "MS", "KY", "OH", "IN",
        "MI", "IA", "WI", "MN", "SD", "ND", "MT", "IL",
        "MO", "KS", "NE", "LA", "AR", "OK", "TX", "CO",
        "WY", "ID", "UT", "AZ", "NM", "NV", "CA", "HI",
        "OR", "WA", "AK", "SG"
      ]

paths:
  /api/states:
    get:
      description: "Returns a list of all states"
      operationId: getStates
      responses:
        200:
          description: "List of all States"
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/states"
        400:
          description: "Error encountered"
          content:
            "text/plain":
              schema:
                type: string

  /api/state/{stateId}:
    get:
      description: "Returns a list of cities from the state"
      operationId: getCityByState
      parameters:
        - name: stateId
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/states"

      responses:
        206:
          description: "Partial list of cities"
          content: 
            "application/json":
              schema:
                type: array
                items:
                  type: string
        400:
          description: "Error encountered"
          content:
            "text/plain":
              schema:
                type: string